# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/2.8.12/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/2.8.12/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/local/Cellar/cmake/2.8.12/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/viharipiratla/repos/btp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/viharipiratla/repos/btp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/2.8.12/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/2.8.12/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/viharipiratla/repos/btp/CMakeFiles /Users/viharipiratla/repos/btp/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/viharipiratla/repos/btp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named OS

# Build rule for target.
OS: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 OS
.PHONY : OS

# fast build rule for target.
OS/fast:
	$(MAKE) -f CMakeFiles/OS.dir/build.make CMakeFiles/OS.dir/build
.PHONY : OS/fast

#=============================================================================
# Target rules for targets named OT

# Build rule for target.
OT: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 OT
.PHONY : OT

# fast build rule for target.
OT/fast:
	$(MAKE) -f CMakeFiles/OT.dir/build.make CMakeFiles/OT.dir/build
.PHONY : OT/fast

#=============================================================================
# Target rules for targets named test

# Build rule for target.
test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test
.PHONY : test

# fast build rule for target.
test/fast:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/build
.PHONY : test/fast

object_segmentation/farneback.o: object_segmentation/farneback.cpp.o
.PHONY : object_segmentation/farneback.o

# target to build an object file
object_segmentation/farneback.cpp.o:
	$(MAKE) -f CMakeFiles/OS.dir/build.make CMakeFiles/OS.dir/object_segmentation/farneback.cpp.o
.PHONY : object_segmentation/farneback.cpp.o

object_segmentation/farneback.i: object_segmentation/farneback.cpp.i
.PHONY : object_segmentation/farneback.i

# target to preprocess a source file
object_segmentation/farneback.cpp.i:
	$(MAKE) -f CMakeFiles/OS.dir/build.make CMakeFiles/OS.dir/object_segmentation/farneback.cpp.i
.PHONY : object_segmentation/farneback.cpp.i

object_segmentation/farneback.s: object_segmentation/farneback.cpp.s
.PHONY : object_segmentation/farneback.s

# target to generate assembly for a file
object_segmentation/farneback.cpp.s:
	$(MAKE) -f CMakeFiles/OS.dir/build.make CMakeFiles/OS.dir/object_segmentation/farneback.cpp.s
.PHONY : object_segmentation/farneback.cpp.s

object_track/lk_based.o: object_track/lk_based.cpp.o
.PHONY : object_track/lk_based.o

# target to build an object file
object_track/lk_based.cpp.o:
	$(MAKE) -f CMakeFiles/OT.dir/build.make CMakeFiles/OT.dir/object_track/lk_based.cpp.o
.PHONY : object_track/lk_based.cpp.o

object_track/lk_based.i: object_track/lk_based.cpp.i
.PHONY : object_track/lk_based.i

# target to preprocess a source file
object_track/lk_based.cpp.i:
	$(MAKE) -f CMakeFiles/OT.dir/build.make CMakeFiles/OT.dir/object_track/lk_based.cpp.i
.PHONY : object_track/lk_based.cpp.i

object_track/lk_based.s: object_track/lk_based.cpp.s
.PHONY : object_track/lk_based.s

# target to generate assembly for a file
object_track/lk_based.cpp.s:
	$(MAKE) -f CMakeFiles/OT.dir/build.make CMakeFiles/OT.dir/object_track/lk_based.cpp.s
.PHONY : object_track/lk_based.cpp.s

reconstruction/VisualHull.o: reconstruction/VisualHull.cpp.o
.PHONY : reconstruction/VisualHull.o

# target to build an object file
reconstruction/VisualHull.cpp.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/reconstruction/VisualHull.cpp.o
.PHONY : reconstruction/VisualHull.cpp.o

reconstruction/VisualHull.i: reconstruction/VisualHull.cpp.i
.PHONY : reconstruction/VisualHull.i

# target to preprocess a source file
reconstruction/VisualHull.cpp.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/reconstruction/VisualHull.cpp.i
.PHONY : reconstruction/VisualHull.cpp.i

reconstruction/VisualHull.s: reconstruction/VisualHull.cpp.s
.PHONY : reconstruction/VisualHull.s

# target to generate assembly for a file
reconstruction/VisualHull.cpp.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/reconstruction/VisualHull.cpp.s
.PHONY : reconstruction/VisualHull.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... OS"
	@echo "... OT"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... object_segmentation/farneback.o"
	@echo "... object_segmentation/farneback.i"
	@echo "... object_segmentation/farneback.s"
	@echo "... object_track/lk_based.o"
	@echo "... object_track/lk_based.i"
	@echo "... object_track/lk_based.s"
	@echo "... reconstruction/VisualHull.o"
	@echo "... reconstruction/VisualHull.i"
	@echo "... reconstruction/VisualHull.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

